=== VijayEluri/weighscore/weighscore-gui/NeuralNetwork.dtd
<!ELEMENT neuralNetwork (translator?, teacher?, neuron+)>

<!ELEMENT translator (field*)>
<!ELEMENT field (pass|translate)>
<!ELEMENT pass (activator)>
<!ELEMENT translate (item+)>
<!ELEMENT item (activator)>
<!ELEMENT activator (range?)>
<!ELEMENT range (#PCDATA)>

<!ELEMENT teacher (parameter*)>
<!ELEMENT neuron (activationFunction?, axon?, statistic?)>
<!ELEMENT axon (synapse+)>
<!ELEMENT synapse (statistic?)>
<!ELEMENT activation (parameter*)>
<!ELEMENT statistic (parameter*)>
<!ELEMENT parameter (#PCDATA)>

<!ATTLIST neuralNetwork
  xmlns:xlink CDATA #REQUIRED>

<!ATTLIST field
  type (ask | answer) #REQUIRED
  name CDATA #REQUIRED>
<!ATTLIST pass
  dividor CDATA #IMPLIED>
<!ATTLIST item
  value CDATA #REQUIRED>
<!ATTLIST activator
  index CDATA #REQUIRED>
<!ATTLIST range
  value CDATA #REQUIRED
  max CDATA #IMPLIED
  min CDATA #IMPLIED>

<!ATTLIST teacher
  class CDATA "SimpleTeacher">
<!ATTLIST neuron
  threshold CDATA #IMPLIED
  input (true|false) "false"
  output (true|false) "false">
<!ATTLIST synapse
  weight CDATA #IMPLIED
  xlink:href CDATA #REQUIRED
  xlink:type (simple|locator) #REQUIRED>
<!ATTLIST activationFunction
  class CDATA "Sigmoid">
<!ATTLIST parameter
  name CDATA #REQUIRED>
<!ATTLIST statistic
  classes CDATA "MomentumStatistic">

=== VijayEluri/weighscore/weighscore/NeuralNetwork.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE neuralNetwork SYSTEM "NeuralNetwork.dtd">
<neuralNetwork xmlns:xlink="http://www.w3.org/1999/xlink" translator="Translator.xml">
  <teacher class="com.weighscore.neuro.EmpiricTeacher">
    <parameter name="learnRate">0.4</parameter>
    <parameter name="momentumCoefficient">0.2</parameter>
  </teacher>
  <neuron input="true">
    <axon>
      <synapse xlink:type="locator" xlink:href="#xpointer(/neuralNetwork/neuron[3])"/>
      <synapse xlink:type="locator" xlink:href="#xpointer(/neuralNetwork/neuron[4])"/>
    </axon>
  </neuron>
  <neuron input="true">
    <axon>
      <synapse xlink:type="locator" xlink:href="#xpointer(/neuralNetwork/neuron[3])"/>
      <synapse xlink:type="locator" xlink:href="#xpointer(/neuralNetwork/neuron[4])"/>
    </axon>
  </neuron>
  <neuron>
    <axon>
      <synapse xlink:type="locator" xlink:href="#xpointer(/neuralNetwork/neuron[5])"/>
    </axon>
  </neuron>
  <neuron>
    <axon>
      <synapse xlink:type="locator" xlink:href="#xpointer(/neuralNetwork/neuron[5])"/>
    </axon>
  </neuron>
  <neuron output="true"/>
</neuralNetwork>
