=== VijayEluri/weighscore/weighscore/Translator.dtd
<!ELEMENT translator (field*)>
<!ELEMENT field (pass|translate)>
<!ELEMENT pass (activator)>
<!ELEMENT translate (item+)>
<!ELEMENT item (activator)>
<!ELEMENT activator (range?)>
<!ELEMENT range (#PCDATA)>

<!ATTLIST field
  type (ask | answer) #REQUIRED
  name CDATA #REQUIRED>
<!ATTLIST pass
  dividor CDATA #IMPLIED>
<!ATTLIST item
  value CDATA #REQUIRED>
<!ATTLIST activator
  index CDATA #REQUIRED>
<!ATTLIST range
  value CDATA #REQUIRED
  max CDATA #IMPLIED
  min CDATA #IMPLIED>

=== VijayEluri/weighscore/weighscore/Translator-simpleApp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE translator SYSTEM "Translator.dtd">
<translator>
  <field name="age" type="ask">
    <pass dividor="200">
      <activator index="1"/>
    </pass>
  </field>
  <field name="gender" type="ask">
    <translate>
      <item value="m">
        <activator index="2">
          <range value="0.5" min="0"/>
        </activator>
      </item>
      <item value="f">
        <activator index="2">
          <range value="-0.5" max="0"/>
        </activator>
      </item>
    </translate>
  </field>
  <field name="income" type="ask">
    <pass dividor="1000000">
      <activator index="3"/>
    </pass>
  </field>
  <field name="education" type="ask">
    <translate>
      <item value="higher">
        <activator index="4">
          <range value="0.5" min="0.01"/>
        </activator>
      </item>
      <item value="high">
        <activator index="5">
          <range value="0.5" min="0.01"/>
        </activator>
      </item>
      <item value="low">
        <activator index="6">
          <range value="0.5" min="0.01"/>
        </activator>
      </item>
    </translate>
  </field>
  <field name="goodbad" type="answer">
    <translate>
      <item value="good">
        <activator index="1">
          <range value="0.5" min="0"/>
        </activator>
      </item>
      <item value="bad">
        <activator index="1">
          <range value="-0.5" max="0"/>
        </activator>
      </item>
    </translate>
  </field>
</translator>

=== VijayEluri/weighscore/weighscore/TransXor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE translator SYSTEM "Translator.dtd">
<translator>
  <field name="x1" type="ask">
    <pass>
      <activator index="1"/>
    </pass>
  </field>
  <field name="x2" type="ask">
    <pass>
      <activator index="2"/>
    </pass>
  </field>
  <field name="result" type="answer">
    <pass>
      <activator index="1"/>
    </pass>
  </field>
</translator>
